dest:
  - src: effe
    dest: modules/effe
  - src: shift
    dest: modules/shi1
modules:
  - name: employees
    repo: git@github.com:jessielaf/effe
    version: master
  - name: shifts
    repo: git@github.com:jessielaf/effe
    version: master
